const CountryNameConverter = ({ countryCode }) => {
  const getCountryName = countryCode => {
    const countryCodes = {
      AF: 'Afghanistan',
      AO: 'Angola',
      AL: 'Albania',
      AE: 'United Arab Emirates',
      AR: 'Argentina',
      AM: 'Armenia',
      TF: 'French Southern Territories',
      AU: 'Australia',
      AT: 'Austria',
      AZ: 'Azerbaijan',
      BI: 'Burundi',
      BE: 'Belgium',
      BJ: 'Benin',
      BF: 'Burkina Faso',
      BD: 'Bangladesh',
      BG: 'Bulgaria',
      BS: 'Bahamas',
      BA: 'Bosnia and Herzegovina',
      BY: 'Belarus',
      BZ: 'Belize',
      BO: 'Bolivia',
      BR: 'Brazil',
      BN: 'Brunei',
      BT: 'Bhutan',
      BW: 'Botswana',
      CF: 'Central African Republic',
      CA: 'Canada',
      CH: 'Switzerland',
      CL: 'Chile',
      CN: 'China',
      CI: "Cote d'Ivoire",
      CM: 'Cameroon',
      CD: 'Democratic Republic of Congo',
      CG: 'Congo',
      CO: 'Colombia',
      CR: 'Costa Rica',
      CU: 'Cuba',
      CY: 'Cyprus',
      CZ: 'Czechia',
      DE: 'Germany',
      DJ: 'Djibouti',
      DK: 'Denmark',
      GL: 'Greenland',
      DO: 'Dominican Republic',
      DZ: 'Algeria',
      EC: 'Ecuador',
      EG: 'Egypt',
      ER: 'Eritrea',
      ES: 'Spain',
      EE: 'Estonia',
      ET: 'Ethiopia',
      FI: 'Finland',
      FJ: 'Fiji',
      FR: 'France',
      GF: 'French Guiana',
      GA: 'Gabon',
      GB: 'United Kingdom',
      GE: 'Georgia',
      GH: 'Ghana',
      GN: 'Guinea',
      GM: 'Gambia',
      GW: 'Guinea-Bissau',
      GQ: 'Equatorial Guinea',
      GR: 'Greece',
      GT: 'Guatemala',
      GY: 'Guyana',
      HN: 'Honduras',
      HR: 'Croatia',
      HT: 'Haiti',
      HU: 'Hungary',
      ID: 'Indonesia',
      IN: 'India',
      IE: 'Ireland',
      IR: 'Iran',
      IQ: 'Iraq',
      IS: 'Iceland',
      IL: 'Israel',
      IT: 'Italy',
      JM: 'Jamaica',
      JO: 'Jordan',
      JP: 'Japan',
      KZ: 'Kazakhstan',
      KE: 'Kenya',
      KG: 'Kyrgyzstan',
      KH: 'Cambodia',
      KR: 'South Korea',
      XK: 'Kosovo',
      KW: 'Kuwait',
      LA: 'Laos',
      LB: 'Lebanon',
      LR: 'Liberia',
      LY: 'Libya',
      LK: 'Sri Lanka',
      LS: 'Lesotho',
      LT: 'Lithuania',
      LU: 'Luxembourg',
      LV: 'Latvia',
      MA: 'Morocco',
      MD: 'Moldova',
      MG: 'Madagascar',
      MX: 'Mexico',
      MK: 'North Macedonia',
      ML: 'Mali',
      MM: 'Myanmar',
      ME: 'Montenegro',
      MN: 'Mongolia',
      MZ: 'Mozambique',
      MR: 'Mauritania',
      MW: 'Malawi',
      MY: 'Malaysia',
      NA: 'Namibia',
      NC: 'New Caledonia',
      NE: 'Niger',
      NG: 'Nigeria',
      NI: 'Nicaragua',
      NL: 'Netherlands',
      NO: 'Norway',
      NP: 'Nepal',
      NZ: 'New Zealand',
      OM: 'Oman',
      PK: 'Pakistan',
      PA: 'Panama',
      PE: 'Peru',
      PH: 'Philippines',
      PG: 'Papua New Guinea',
      PL: 'Poland',
      PR: 'Puerto Rico',
      KP: 'North Korea',
      PT: 'Portugal',
      PY: 'Paraguay',
      QA: 'Qatar',
      RO: 'Romania',
      RU: 'Russia',
      RW: 'Rwanda',
      EH: 'Western Sahara',
      SA: 'Saudi Arabia',
      SD: 'Sudan',
      SS: 'South Sudan',
      SN: 'Senegal',
      SB: 'Solomon Islands',
      SL: 'Sierra Leone',
      SV: 'El Salvador',
      SO: 'Somalia',
      RS: 'Serbia',
      SR: 'Suriname',
      SK: 'Slovakia',
      SI: 'Slovenia',
      SE: 'Sweden',
      SZ: 'Eswatini',
      SY: 'Syria',
      TD: 'Chad',
      TG: 'Togo',
      TH: 'Thailand',
      TJ: 'Tajikistan',
      TM: 'Turkmenistan',
      TL: 'Timor',
      TT: 'Trinidad and Tobago',
      TN: 'Tunisia',
      TR: 'Turkey',
      TW: 'Taiwan',
      TZ: 'Tanzania',
      UG: 'Uganda',
      UA: 'Ukraine',
      UY: 'Uruguay',
      US: 'United States',
      UZ: 'Uzbekistan',
      VE: 'Venezuela',
      VN: 'Vietnam',
      VU: 'Vanuatu',
      PS: 'Palestine',
      YE: 'Yemen',
      ZA: 'South Africa',
      ZM: 'Zambia',
      ZW: 'Zimbabwe',
      CV: 'Cape Verde',
      KM: 'Comoros',
      MU: 'Mauritius',
      SC: 'Seychelles',
      BH: 'Bahrain',
      MV: 'Maldives',
      MH: 'Marshall Islands',
      FM: 'Micronesia (country)',
      NR: 'Nauru',
      PW: 'Palau',
      WS: 'Samoa',
      SG: 'Singapore',
      TO: 'Tonga',
      TV: 'Tuvalu',
      AG: 'Antigua and Barbuda',
      BB: 'Barbados',
      DM: 'Dominica',
      GD: 'Grenada',
      KN: 'Saint Kitts and Nevis',
      LC: 'Saint Lucia',
      VC: 'Saint Vincent and the Grenadines',
      AD: 'Andorra',
      LI: 'Liechtenstein',
      MT: 'Malta',
      MC: 'Monaco',
      SM: 'San Marino',
      KI: 'Kiribati',
      ST: 'Sao Tome and Principe',
    };

    const countryName = countryCodes[countryCode];

    if (!countryName) {
      return 'Country not found';
    }

    const urlFriendlyName = countryName.replace(/\s+/g, '-') || 'unknown';

    return urlFriendlyName;
  };

  return getCountryName(countryCode);
};

export default CountryNameConverter;
